### ISSUE TITLE
Cynosa Chroma support

### ISSUE THREAD

**Issue by alh61** [moozhub/yum-repo-mooz#3] opened 2018-07-12 23:24 UTC
I just bought a Cynosa Chroma keyboard.
Support for this has just been added in the new 2.3.1 driver.
Could you please update the package for Centos ?

**Comment by moozhub** [comment] 2018-07-13 07:35
Updated package in the repo now. Feel free to open this back up if you have a issue installing it or having a issue with the new device being detected.

**Comment by alh61** [comment] 2018-07-26 22:02
Thanks for the update - and sorry for being a little late with the comments here.
I tried the driver just after you uploaded it - but I had same problem as issue #1 
As I use this pc as a small server too - not working keyboard was a big issue,
so I uninstalled it again (via vnc).

Now found some time to test it again - on another test partition, and
found an extra old PS/2 keyboard, so I can do something, when it fails :-)

I only installed openrazer-meta on this test partition - and all dependencies.

After reboot, keyboard stopped working as before, and as in #1 
Since this is different hw, I write here.

I then installed hid-replay pkg - and run hid-recorder as suggested in #1 
Keyboard started working immediately !

So far so good - but after reboot problem is back - and without a keyboard
it is hard to login and run hid-recorder.

What can I do to help trace this problem ?

**Comment by moozhub** [comment] 2018-07-27 20:50
Is there a way you can bring up a Fedora 25 test environment and test your hardware with it using the driver from https://openrazer.github.io/#fedora ? I think that will ultimately answer some questions on whether this is all CentOS's fault since the SPEC file I'm using is very similar to the Fedora one aside from a few packages that had to be built because they didn't exist in any other repo..

**Comment by alh61** [comment] 2018-07-27 21:57
I just recent got a extra SSD to put into the system - just need to install it, and yes, then I can
test Fedora - but I think I'll try F28 if that is ok.
After I now can get keyb to work after starting hid-recorder - I installed polychromatic.
that app doesn't work at all - I only get a black window on the screen, when i try to start the controller.

I'll try to get Fedora installed quickly.

**Comment by moozhub** [comment] 2018-07-27 22:35
OK. Yeah that's pretty strange, the problem seems to be with certain devices but have no idea why. Is there any output when running polychromatic from the commandline? There's a log for openrazer as well that may shed some light at `~/.local/share/openrazer/logs/razer.log`

**Comment by alh61** [comment] 2018-07-27 22:45
Yeah, a mile long messages from polychomatic-controller - I'll be back on that.

The razer .log says:

2018-07-27 23:32:31 | razer                          | CRITICAL | User is not a member of the plugdev group
2018-07-27 23:34:22 | razer                          | CRITICAL | User is not a member of the plugdev group
2018-07-27 23:36:10 | razer                          | CRITICAL | User is not a member of the plugdev group

**Comment by moozhub** [comment] 2018-07-27 22:45
Also your black screen problem sounds a lot like this: https://github.com/polychromatic/polychromatic/issues/158

**Comment by moozhub** [comment] 2018-07-27 22:47
> 2018-07-27 23:32:31 | razer | CRITICAL | User is not a member of the plugdev group

After installation of the RPM it should have echo'd that you need to add your user to that group. You can do this by: `sudo gpasswd -a <yourUsername> plugdev` ... After you do this you have to log out of your current session and log back in..

**Comment by alh61** [comment] 2018-07-27 23:18
Ah, I use Yumex to install packages - so I don't get such messages :-/ sorry about that.
Added myself.

after reboot - the log is now 16k - as afaics - no errors

Polychromatic tray icon is not red but white and the popup menu from it is 
generally working. trying to open controller still gives either a black or white
window. 

Selecting effects from menu however does work - sp we are on the right track.

BTW I have put hid-recorder into rc.d to make keyb work at boot time.

**Comment by alh61** [comment] 2018-07-27 23:30
Well your hint to #158 about black screen - webkitgtk4 crash every time I launch P-C so yes, it seems related. 

Will reboot now without hid-recorder

**Comment by alh61** [comment] 2018-07-27 23:47
I removed hid-recorder from rc.d and it was of course impossible to login again. As the add of plugdev group only changes something after login with my ID.

To be sure I added plugdev group to root - and rebooted - didn't change anything, keyb didn't work

**Comment by moozhub** [comment] 2018-07-27 23:57
What display manager / greeter are you using for login's? (eg. lightdm)

**Comment by alh61** [comment] 2018-07-28 00:05
lightdm and KDE for desktop - on this test partition

**Comment by moozhub** [comment] 2018-07-28 02:06
You can always have lightdm log you in automatically from boot...but honestly don't think it would change much. Let me know when you've had a chance with F28, for all intents and purposes try to retain the same type of setup that you have on CentOS.

**Comment by alh61** [comment] 2018-07-28 19:39
I have put an extra keyboard on PS2  connector - so I do not get trapped :-)
Creating the USB stick now to install F28 KDE

**Comment by alh61** [comment] 2018-07-28 22:42
OK. F28 installed and updated. Driver installed from Suse F28 repo. REbooted, keyboard still works.

**Comment by alh61** [comment] 2018-07-28 23:01
tried to install polychromatic too. That doesn't seem to work - the daemon isn't running

**Comment by moozhub** [comment] 2018-07-29 00:49
All right.. well just to be certain, you are using the EPEL repo in combination with mine, yes? If so, I will bring up a test environment of my own in CentOS to see if I can reproduce the issue myself, because I don't understand why it would be working for both of my devices and not others at this point other than maybe I had to do something special and forgot about it. Not having the same device doesn't help much either, and the documentation as far as version requirements for this software isn't the best right now. Thanks for the info thus far.

**Comment by alh61** [comment] 2018-07-29 01:17
Yes - EPEL is always online here.
Status on Centos 7 is now:
After installing  the the openrazer-meta  driver - I need to add/run hid-recorder to get keyboard working.
If I install polychromatic - then the daemon works after pludev group is added - but only
the tray icon app works.

The GUI app just shows  a black or white window.

As I see in Fedora, that this windows shows some sort of circular animatition during init;
maybe it is some sort af missing dependency to show that --  well just a guess.

**Comment by moozhub** [comment] 2018-07-29 02:05
Well, I found a solution and was sorta something I suspected.. if you want this problem to go away upgrade your kernel to something 4.11 or above. There appears to be some HID fixes that were put in place in the 4.x kernel that resolved issues with certain keyboards and mice. There may be a boot flag (or something) that could be passed to the stock CentOS kernel but I'd have to investigate that..

Easiest way to upgrade the kernel on CentOS is to install `kernel-ml` from the [ELrepo repository](http://elrepo.org/tiki/kernel-ml).

EDIT: Remember that after updating to a new kernel you need to rerun `sudo dkms --force install openrazer-driver/2.3.1`

EDIT2: OK, so I found another work around for the boot flag on the stock CentOS kernel. Here's how you can try if you don't want to upgrade your kernel:

`sudo vim /etc/default/grub`

Append to the `GRUB_CMDLINE_LINUX` the following.. in your case it would be: `usbhid.quirks=0x1532:0x022A:0x20000000` (you can get the device IDs for your mouse or keyboard at the front page of https://github.com/openrazer/openrazer ... just prefix the ID's with the hex term 0x )

`sudo grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg`

Reboot into stock kernel.

Keyboard should work..

**Comment by alh61** [comment] 2018-07-29 14:30
I just tried to remove hid-recorder, and inserted that quirk into grub.cfg
That unfortunately didn't work.

**Comment by alh61** [comment] 2018-07-29 21:01
removed the quirk from grub.cfg again, and upgraded to kernel-ml (4.17.11).
That does indeed fix the keyboard problem; but I'm not sure this is possible on
my main partition - as this uses AMD's amdgpu driver.

**Comment by alh61** [comment] 2018-07-29 21:10
Poly-controller still only shows black screen with kernel-ml
and it crashes webkitgtk4 with both kernels

**Comment by moozhub** [comment] 2018-07-29 22:53
Are there any razerkbd type complaints in dmesg or journalctl? Mine had something like this in the kernel that gave me a idea of what quirk to use:

`kernel: razerkbd 0003:1532:0216.0005: usb_submit_urb(ctrl) failed`

None the less...without really digging into the debug calls for HID, there are a few other quirks that you can try here: https://elixir.bootlin.com/linux/v3.10.1/source/include/linux/hid.h#L273

Just remember to put them into the same format as I suggested above.. but from what it would appear, the razer driver doesn't seem to work in the latest CentOS kernel. I'll write up a issue with them to see if there's something they can do, but kinda doubt it..

**Comment by alh61** [comment] 2018-07-30 11:40
No, there are no error msgs about razer in any logs.

About the quirks - I started testing them all, and voila:
usbhid.quirks=0x1532:0x022A:0x00000040
seems to do the trick - now the keyboard works all the time :-)

Thx for all you help

If I start poluchromatic app it crashes with this in the log:
Jul 30 13:36:11 mail2 kernel: ositorWorkQueue[2895]: segfault at 60 ip 00007f9b8cc6d344 sp 00007f9b219fe680 error 4 in libGL.so.1.2.0[7f9b8cc53000+6e000]
Jul 30 13:36:11 mail2 abrt-hook-ccpp: Process 2869 (WebKitWebProcess) of user 1000 killed by SIGSEGV - dumping core
Jul 30 13:36:11 mail2 abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Jul 30 13:36:12 mail2 abrt-server: Generating core_backtrace

**Comment by moozhub** [comment] 2018-07-30 11:55
You'll probably want to report your findings to the polychromatic developers in the issue I mentioned above since they seem to be aware that it's a possible issue with Webkit. I haven't been able to reproduce this.

**Comment by alh61** [comment] 2018-07-30 22:07
That is interesting, as it doesn't work on both my partitions.
Ar you using KDE ?
I'll take a look at that issue a bit l8r

**Comment by moozhub** [comment] 2018-07-30 22:12
I'm using MATE. It might be something to do with your graphics driver since it's segfaulting in libGL, but I can't be certain. I'm using combination setup of nvidia's proprietary driver and intel's opensource driver.

**Comment by alh61** [comment] 2018-07-30 23:06
ok, interesting. I have MATE installed too on one of the partitions - just haven't used it for some time.
I have an AMD soc chip here - used to have AMD drivers loaded for that, but for some reason
they failed recently, and I had to manually get a bunch of driver out, to get it back to kenel radeon driver.
Seems an idea to try to reinstall the AMD driver, and/or try MATE too. Ill give these combinations
another try.

**Comment by alh61** [comment] 2018-07-31 16:32
todays updated version can't be installed - it requires a package 'xautomation'
which I don't see in any repo

**Comment by moozhub** [comment] 2018-07-31 20:33
Yes, there's a issue with my repo at the moment... I will fix it shortly

**Comment by moozhub** [comment] 2018-07-31 20:49
xautomation should be there now ... going to close this unless you're having other issues..

**Closed as completed by moozhub** 2018-07-31 20:49 UTC

**Comment by alh61** [comment] 2018-08-01 06:15
Great. I preinstalled the quirk before installing the driver.
After install, all works now - both keyboard and poly-controller app,
and this is with the radeon driver, where it didn't work before.
Nice job, Moozhub !!!
